### ISSUE TITLE
[Enhancement]Increase log level only in current script

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#275] opened 2017-03-05 11:06 UTC
Also during development of inline php devices, it would be great if I could increase/overwrite the log level only for the current script.
Currently I have to update all the debug log statements to i.e. warning level to only debug something for one device. If i just could increase the log level at the top of the script would be handy for debugging single devices/scripts.

Don't know if this is easy to implement. Because I assume the logging stuff is just forwarded to the general logging implementation of homegear. Probably just the `Homegear::log` method could be adapted to support such a feature.

**Comment by spali** [comment] 2017-03-05 11:06
related to #194

**Comment by hfedcba** [comment] 2017-03-06 20:55
Done. The method's name is "setScriptLogLevel()" and must be called from the main thread.

**Comment by spali** [comment] 2017-03-06 21:31
thanks

**Comment by spali** [comment] 2017-03-09 15:06
is the peer id of a second thread known to homegear itself?
Because I realized, that logging of the thread does not include the peer id as the main thread of the peer.
here an example (first line is from the main thread and second from the event thread).
```
03/09/17 15:59:56.277 Script log (peer id: 210): initializing peer device
03/09/17 15:59:56.299 Script log: initializing peer event thread
```
not really a problem, but I also realized, that setScriptLogLevel() is only set within a thread. So setting it in the main thread, it does not get inherited by the event thread.

**Comment by hfedcba** [comment] 2017-03-18 13:09
I need to look into it.

**Comment by hfedcba** [comment] 2017-03-18 18:44
> is the peer id of a second thread known to homegear itself?

It wasn't but now it is (after calling `registerThread()`).

> So setting it in the main thread, it does not get inherited by the event thread.

That shoudn't be the case - just tested it again. When set before the event thread is created, the event thread should inherit the setting - again `registerThread()` needs to be called.

**Comment by hfedcba** [comment] 2017-04-07 10:18
I'm closing this issue as I can't reproduce it.

**Closed by hfedcba** 2017-04-07 10:18 UTC
Labels: enhancement
