### ISSUE TITLE
HM-LGW sends "Connection closed" every five minutes

### ISSUE THREAD

**Issue by pauxus** [Homegear/Homegear#270] opened 2017-01-20 15:25 UTC
Since I switched from 0.6.13 to 0.6.14, the log says "Connection closed" for my HM-LGW every 5 minutes.

**Comment by hfedcba** [comment] 2017-01-21 07:33
Can you send me the homegear.log?

**Comment by pauxus** [comment] 2017-01-22 19:48
Sent you a link via email.

One thing that I noticed is that the log identifies the firmware of the LGW as 1.0.6, while NetFinder reports it as 1.1.5

**Comment by hfedcba** [comment] 2017-01-23 09:21
I can confirm it's a bug and will look into it. Probably the HM-CFG-LAN has the same problem.

> One thing that I noticed is that the log identifies the firmware of the LGW as 1.0.6, while NetFinder reports it as 1.1.5

That's not the reason for the problem, but still interesting. Homegear directly prints the version number received after sending a "version-request packet". As the versions are not treated differently, is shouldn't matter for communication with Homegear. You could install version 1.1.5 again and see if the correct version number is shown then? Having 1.1.5 is important as 1.0.6 had some bugs.

Cheers,

Sathya

**Comment by hfedcba** [comment] 2017-01-23 10:02
Found the problem. Because of the changed init procedure in 0.6.14 the LAN-GW sends two types of keep alive responses now. The second one was ignored and Homegear thought the gateway was not reachable anymore. It's fixed in the next dev and stable version.

Thank you for reporting this!

**Closed by hfedcba** 2017-01-23 10:02 UTC
Labels: bug

**Comment by danielperna84** [comment] 2017-01-23 14:48
The HM-CFG-USB may be affected by this as well ([Help needed: Homematic UI Toggle flips back](https://community.home-assistant.io/t/help-needed-homematic-ui-toggle-flips-back/8289)). Just wanted to point that out in case this would require additional changes.
