### ISSUE TITLE
reusing peer id of just deleted device

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#236] opened 2015-10-05 19:04 UTC
In my setup script to setup "virtual" devices, I do the following:
 - delete device
 - create device with ```createDevice```
 - use ```setId``` to set the id to the same as before the delete.

At least on my virtual device I get a "New peer ID is already in use" error.
If I put a sleep of one second before ```setId``` it works.
There seems to be some concurrent problem that the devices isn't delete completely after ```deleteDevice``` returns.

**Comment by hfedcba** [comment] 2015-10-06 11:59
Thank you! I can reproduce the problem here.

**Comment by hfedcba** [comment] 2015-10-06 12:34
The problem was the buffered database. setId checked in the database if the peer exists. But directly after calling deleteDevice the peer was still there. It's fixed now ;-).

**Closed** 2015-10-06 12:45 UTC
Labels: bug
